services:
  postgres:
    # TODO switch back to official postgis image when arm64 is supported
    image: ghcr.io/baosystems/postgis:18-3.6@sha256:f6394ead4b19db862baba5ca35d1c6fc07f676feca9f72737a6f31a220d2bdc1
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_DB: dossier-root
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
