version: "3.8"
services:
  postgres:
    image: postgis/postgis:13-3.0-alpine
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_DB: datadata-core-test
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
