services:
  postgres:
    # TODO switch back to official postgis image when arm64 is supported
    image: ghcr.io/baosystems/postgis:18-3.6
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_DB: dossier-root
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
