version: "3.8"
services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_DB: dossier-root
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
