packages:
  - "apps/*"
  - "examples/*"
  - "libraries/*"
  - "templates/*"
  - "tools/*"

minimumReleaseAge: 1440
blockExoticSubdeps: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "better-sqlite3"
  - "esbuild"
  - "oxc-resolver"
  - "sharp"

overrides:
  "@babel/core@7.26.9": "7.26.10"
  "@babel/helpers@7.26.9": "7.26.10"
  "@babel/runtime@7.26.9": "7.26.10"
  "@modelcontextprotocol/sdk@1.17.2": "~1.25.2"
  "postcss@5.2.18": "8.4.31"
  "tar-fs@2.1.3": "~2.1.4"
  "vite@6.2.7": "~6.4.1"
