name: Browser Integration Tests
on: [push]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  build:
    name: Browser integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 16
    steps:
      - name: apt-get update
        run: sudo apt-get update # to avoid error when installing Playwright
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: |
          cd libraries/sql.js-browser-integration-test
          npx playwright install --with-deps chromium firefox webkit
          cd ../react-components2
          npx playwright install --with-deps chromium firefox webkit
      - name: build
        run: |
          npx turbo run --filter=@dossierhq/sql.js-browser-integration-test --filter=@dossierhq/react-components2 lint check-types build test test-integration
        env:
          TURBO_TEAM: ${{ secrets.DOSSIERHQ_TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.DOSSIERHQ_TURBO_TOKEN }}
      - name: Run Chromatic for react-components2
        uses: chromaui/action@31fa436e1ba57b2e5498d7798e0b49f53711db0c # v17.4.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: libraries/react-components2
      - name: Serve Storybook and run tests
        run: |
          cd libraries/react-components2
          npm run build-storybook
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6008 --silent" \
            "npx wait-on tcp:6008 && npm run test:storybook"
